name: Rust CI

on:
  push:
    branches: [main]
    paths: ['cli/**/*']
  pull_request:
    paths: ['cli/**/*']

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies for DBus
        run: |
          sudo apt update -y
          sudo apt install -y libdbus-1-dev pkg-config

      - name: Start dbus-daemon (for headless testing)
        run: |
          sudo dbus-daemon --session --nofork --print-address &
          export DBUS_SESSION_BUS_ADDRESS=$(sudo dbus-daemon --session --nofork --print-address)

      - name: Run cargo test
        run: cargo test --all-features

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: stable

      - name: Run rustfmt Check
        run: cargo fmt --check
